In [ ]:
import numpy as np

#Pandas
Is another module. It's main goal is data manipulation and analysis in Python. It includes new data structures and operations to manipulate data tables.

In [ ]:
import pandas as pd

##Series
Series are one-dimensional data structures, like lists or arrays in numpy. What differentiates the series is that the index of each element can be a label that we assign, similar to what is done in dictionaries. To create a series we use the Series() method where we will add the values and, if we want, the custom indices.

In [ ]:
my_series=pd.Series(np.array([1,2,3,4,5]), index=['a', 'b', 'c', 'd', 'e'])
print(my_series)

series1=pd.Series(np.array([1, 2, 3, 4, 5]), index=['a', 'b', 'c', 'd', 'e'])
print(series1)

a_dictionary={'a':7,'b':8,'c':9}
series2=pd.Series(a_dictionary)
print(series2)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    7
b    8
c    9
dtype: int64

we can access series by index, range or position

In [ ]:
print(series1['a'])
print(series1[3])
print(series1[:2])

1
4
a    1
b    2
dtype: int64

In [ ]:
print(series1.index)
print(series1.values)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]

Series are based on numpy arrays. For this reason, we can easily apply vectorized operations, just like we did with arrays in numpy. However, it is important that both strings have the same indices, otherwise they may return unexpected results.

In [ ]:
result=series1+series2
print(result)

print(series1*5)
print(np.sqrt(series1))

a     8.0
b    10.0
c    12.0
d     NaN
e     NaN
dtype: float64
a     5
b    10
c    15
d    20
e    25
dtype: int64
a    1.000000
b    1.414214
c    1.732051
d    2.000000
e    2.236068
dtype: float64

#Dataframe 
Dataframes are the most used structure in pandas. These dataframes are a two-dimensional structure of labeled data, that is, they represent a table where each position of said table has a label in the row and another label in the column. There are many ways to build dataframes. They all use pandas's DataFrame() function. 
For example, we can build a dataframe from a dictionary that stores two strings:

In [ ]:
a_dict={'col1': pd.Series([1,2,3], index=['a','b','c']),
       'col2': pd.Series([5,6,8], index=['a','b','d'])}
df_small=pd.DataFrame(a_dict)
df_small

   col1  col2
a   1.0   5.0
b   2.0   6.0
c   3.0   NaN
d   NaN   8.0

Another possible way to create a dataframe is through a list of dictionaries:

In [ ]:
mylist=[{'a':1,'b':2,'c':5}]
df_small2=pd.DataFrame(mylist)
df_small2

   a  b  c
0  1  2  5

You can create a dataframe from a csv file. In some cases, these csv files include headers. In some other, they don't, so you have to create them. By default, the read_csv function assumes the file has headers

In [ ]:
import pandas as pd
import requests


url1 = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
url2 = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/heart-disease.names"
df = pd.read_csv(url1, header=None)
df.columns=['age','sex','chest_pain_type',
            'rest_blood_pressure','serum_cholesterol',
            'fasting_blood_sugar','rest_ecg','max_HR_achieved',
            'exercise_induced_angina','ST_depression','ST_slope','vessels_fluoroscopy','thal','heart_disease']

df_info = requests.get(url2).text

The dataset we downloaded is hosted at the UCI repository. In order to now more about it, we have also fetched the text file that describes in detail what information we can find in this dataset

In [ ]:
print(df_info)

Publication Request:
   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
   This file describes the contents of the heart-disease directory.

   This directory contains 4 databases concerning heart disease diagnosis.
   All attributes are numeric-valued.  The data was collected from the
   four following locations:

     1. Cleveland Clinic Foundation (cleveland.data)
     2. Hungarian Institute of Cardiology, Budapest (hungarian.data)
     3. V.A. Medical Center, Long Beach, CA (long-beach-va.data)
     4. University Hospital, Zurich, Switzerland (switzerland.data)

   Each database has the same instance format.  While the databases have 76
   raw attributes, only 14 of them are actually used.  Thus I've taken the
   liberty of making 2 copies of each database: one with all the attributes
   and 1 with the 14 attributes actually used in past experiments.

   The authors of the databases have requested:

      ...that any publications resulting from the use of the data include the
      names of the principal investigator responsible for the data collection
      at each institution.  They would be:

       1. Hungarian Institute of Cardiology. Budapest: Andras Janosi, M.D.
       2. University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.
       3. University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.
       4. V.A. Medical Center, Long Beach and Cleveland Clinic Foundation:
	  Robert Detrano, M.D., Ph.D.

   Thanks in advance for abiding by this request.

   David Aha
   July 22, 1988
   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

1. Title: Heart Disease Databases

2. Source Information:
   (a) Creators:
       -- 1. Hungarian Institute of Cardiology. Budapest: Andras Janosi, M.D.
       -- 2. University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.
       -- 3. University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.
       -- 4. V.A. Medical Center, Long Beach and Cleveland Clinic Foundation:
             Robert Detrano, M.D., Ph.D.
   (b) Donor: David W. Aha (aha@ics.uci.edu) (714) 856-8779
   (c) Date: July, 1988

3. Past Usage:
    1. Detrano,~R., Janosi,~A., Steinbrunn,~W., Pfisterer,~M., Schmid,~J.,
       Sandhu,~S., Guppy,~K., Lee,~S., \& Froelicher,~V. (1989).  {\it
       International application of a new probability algorithm for the
       diagnosis of coronary artery disease.}  {\it American Journal of
       Cardiology}, {\it 64},304--310.
       -- International Probability Analysis
       -- Address: Robert Detrano, M.D.
                   Cardiology 111-C
                   V.A. Medical Center
                   5901 E. 7th Street
                   Long Beach, CA 90028
       -- Results in percent accuracy: (for 0.5 probability threshold)
             Data Name:  CDF    CADENZA
          -- Hungarian   77     74
             Long beach  79     77
             Swiss       81     81
          -- Approximately a 77% correct classification accuracy with a
             logistic-regression-derived discriminant function
    2. David W. Aha & Dennis Kibler
       --


          -- Instance-based prediction of heart-disease presence with the
             Cleveland database
             -- NTgrowth: 77.0% accuracy
             --       C4: 74.8% accuracy
    3. John Gennari
       -- Gennari, J.~H., Langley, P, \& Fisher, D. (1989). Models of
          incremental concept formation. {\it Artificial Intelligence, 40},
          11--61.
       -- Results:
          -- The CLASSIT conceptual clustering system achieved a 78.9% accuracy
             on the Cleveland database.

4. Relevant Information:
     This database contains 76 attributes, but all published experiments
     refer to using a subset of 14 of them.  In particular, the Cleveland
     database is the only one that has been used by ML researchers to
     this date.  The "goal" field refers to the presence of heart disease
     in the patient.  It is integer valued from 0 (no presence) to 4.
     Experiments with the Cleveland database have concentrated on simply
     attempting to distinguish presence (values 1,2,3,4) from absence (value
     0).

     The names and social security numbers of the patients were recently
     removed from the database, replaced with dummy values.

     One file has been "processed", that one containing the Cleveland
     database.  All four unprocessed files also exist in this directory.

5. Number of Instances:
        Database:    # of instances:
          Cleveland: 303
          Hungarian: 294
        Switzerland: 123
      Long Beach VA: 200

6. Number of Attributes: 76 (including the predicted attribute)

7. Attribute Information:
   -- Only 14 used
      -- 1. #3  (age)
      -- 2. #4  (sex)
      -- 3. #9  (cp)
      -- 4. #10 (trestbps)
      -- 5. #12 (chol)
      -- 6. #16 (fbs)
      -- 7. #19 (restecg)
      -- 8. #32 (thalach)
      -- 9. #38 (exang)
      -- 10. #40 (oldpeak)
      -- 11. #41 (slope)
      -- 12. #44 (ca)
      -- 13. #51 (thal)
      -- 14. #58 (num)       (the predicted attribute)

   -- Complete attribute documentation:
      1 id: patient identification number
      2 ccf: social security number (I replaced this with a dummy value of 0)
      3 age: age in years
      4 sex: sex (1 = male; 0 = female)
      5 painloc: chest pain location (1 = substernal; 0 = otherwise)
      6 painexer (1 = provoked by exertion; 0 = otherwise)
      7 relrest (1 = relieved after rest; 0 = otherwise)
      8 pncaden (sum of 5, 6, and 7)
      9 cp: chest pain type
        -- Value 1: typical angina
        -- Value 2: atypical angina
        -- Value 3: non-anginal pain
        -- Value 4: asymptomatic
     10 trestbps: resting blood pressure (in mm Hg on admission to the
        hospital)
     11 htn
     12 chol: serum cholestoral in mg/dl
     13 smoke: I believe this is 1 = yes; 0 = no (is or is not a smoker)
     14 cigs (cigarettes per day)
     15 years (number of years as a smoker)
     16 fbs: (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false)
     17 dm (1 = history of diabetes; 0 = no such history)
     18 famhist: family history of coronary artery disease (1 = yes; 0 = no)
     19 restecg: resting electrocardiographic results
        -- Value 0: normal
        -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST
                    elevation or depression of > 0.05 mV)
        -- Value 2: showing probable or definite left ventricular hypertrophy
                    by Estes' criteria
     20 ekgmo (month of exercise ECG reading)
     21 ekgday(day of exercise ECG reading)
     22 ekgyr (year of exercise ECG reading)
     23 dig (digitalis used furing exercise ECG: 1 = yes; 0 = no)
     24 prop (Beta blocker used during exercise ECG: 1 = yes; 0 = no)
     25 nitr (nitrates used during exercise ECG: 1 = yes; 0 = no)
     26 pro (calcium channel blocker used during exercise ECG: 1 = yes; 0 = no)
     27 diuretic (diuretic used used during exercise ECG: 1 = yes; 0 = no)
     28 proto: exercise protocol
          1 = Bruce
          2 = Kottus
          3 = McHenry
          4 = fast Balke
          5 = Balke
          6 = Noughton
          7 = bike 150 kpa min/min  (Not sure if "kpa min/min" is what was
              written!)
          8 = bike 125 kpa min/min
          9 = bike 100 kpa min/min
         10 = bike 75 kpa min/min
         11 = bike 50 kpa min/min
         12 = arm ergometer
     29 thaldur: duration of exercise test in minutes
     30 thaltime: time when ST measure depression was noted
     31 met: mets achieved
     32 thalach: maximum heart rate achieved
     33 thalrest: resting heart rate
     34 tpeakbps: peak exercise blood pressure (first of 2 parts)
     35 tpeakbpd: peak exercise blood pressure (second of 2 parts)
     36 dummy
     37 trestbpd: resting blood pressure
     38 exang: exercise induced angina (1 = yes; 0 = no)
     39 xhypo: (1 = yes; 0 = no)
     40 oldpeak = ST depression induced by exercise relative to rest
     41 slope: the slope of the peak exercise ST segment
        -- Value 1: upsloping
        -- Value 2: flat
        -- Value 3: downsloping
     42 rldv5: height at rest
     43 rldv5e: height at peak exercise
     44 ca: number of major vessels (0-3) colored by flourosopy
     45 restckm: irrelevant
     46 exerckm: irrelevant
     47 restef: rest raidonuclid (sp?) ejection fraction
     48 restwm: rest wall (sp?) motion abnormality
        0 = none
        1 = mild or moderate
        2 = moderate or severe
        3 = akinesis or dyskmem (sp?)
     49 exeref: exercise radinalid (sp?) ejection fraction
     50 exerwm: exercise wall (sp?) motion
     51 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect
     52 thalsev: not used
     53 thalpul: not used
     54 earlobe: not used
     55 cmo: month of cardiac cath (sp?)  (perhaps "call")
     56 cday: day of cardiac cath (sp?)
     57 cyr: year of cardiac cath (sp?)
     58 num: diagnosis of heart disease (angiographic disease status)
        -- Value 0: < 50% diameter narrowing
        -- Value 1: > 50% diameter narrowing
        (in any major vessel: attributes 59 through 68 are vessels)
     59 lmt
     60 ladprox
     61 laddist
     62 diag
     63 cxmain
     64 ramus
     65 om1
     66 om2
     67 rcaprox
     68 rcadist
     69 lvx1: not used
     70 lvx2: not used
     71 lvx3: not used
     72 lvx4: not used
     73 lvf: not used
     74 cathef: not used
     75 junk: not used
     76 name: last name of patient
	(I replaced this with the dummy string "name")

9. Missing Attribute Values: Several.  Distinguished with value -9.0.

10. Class Distribution:
        Database:      0   1   2   3   4 Total
          Cleveland: 164  55  36  35  13   303
          Hungarian: 188  37  26  28  15   294
        Switzerland:   8  48  32  30   5   123
      Long Beach VA:  51  56  41  42  10   200

We can select columns from the dataframe by their column header

In [ ]:
df['rest_blood_pressure']

0      145.0
1      160.0
2      120.0
3      130.0
4      130.0
       ...
298    110.0
299    144.0
300    130.0
301    130.0
302    138.0
Name: rest_blood_pressure, Length: 303, dtype: float64

And we can also select rows by their index

In [ ]:
print(df.loc[302])
print(df_small.loc['a'])
print(df_small.iloc[1])

age                         38.0
sex                          1.0
chest_pain_type              3.0
rest_blood_pressure        138.0
serum_cholesterol          175.0
fasting_blood_sugar          0.0
rest_ecg                     0.0
max_HR_achieved            173.0
exercise_induced_angina      0.0
ST_depression                0.0
ST_slope                     1.0
vessels_fluoroscopy            ?
thal                         3.0
heart_disease                  0
Name: 302, dtype: object
col1    1.0
col2    5.0
Name: a, dtype: float64
col1    2.0
col2    6.0
Name: b, dtype: float64

We can add new columns, containing constant values or containing Series (if they have a different number of elements these will be considered NaN)

In [ ]:
df['new_col']=5
df['new_col2']=pd.Series([*range(300)])
df

,age,sex,chest_pain_type,rest_blood_pressure,serum_cholesterol,fasting_blood_sugar,rest_ecg,max_HR_achieved,exercise_induced_angina,ST_depression,ST_slope,vessels_fluoroscopy,thal,heart_disease,new_col,new_col2
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0,5,0.0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2,5,1.0
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1,5,2.0
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0,5,3.0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0,5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1,5,298.0
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2,5,299.0
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3,5,NaN
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1,5,NaN
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0,5,NaN

We can also erase columns using their header (label)

In [ ]:
del df['new_col']
df

,age,sex,chest_pain_type,rest_blood_pressure,serum_cholesterol,fasting_blood_sugar,rest_ecg,max_HR_achieved,exercise_induced_angina,ST_depression,ST_slope,vessels_fluoroscopy,thal,heart_disease,new_col2
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0,0.0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2,1.0
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1,2.0
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0,3.0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1,298.0
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2,299.0
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3,NaN
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1,NaN
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0,NaN

And we can apply different functions to a subgroup of columns. If these are boolean functions, we can use them to filter the elements of the dataframe

In [ ]:
filtro=np.greater_equal(df.ST_depression,df.ST_slope)
df[filtro]

,age,sex,chest_pain_type,rest_blood_pressure,serum_cholesterol,fasting_blood_sugar,rest_ecg,max_HR_achieved,exercise_induced_angina,ST_depression,ST_slope,vessels_fluoroscopy,thal,heart_disease,new_col2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1,2.0
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0,3.0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0,4.0
6,62.0,0.0,4.0,140.0,268.0,0.0,2.0,160.0,0.0,3.6,3.0,2.0,3.0,3,6.0
9,53.0,1.0,4.0,140.0,203.0,1.0,2.0,155.0,1.0,3.1,3.0,0.0,7.0,1,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,58.0,1.0,4.0,114.0,318.0,0.0,1.0,140.0,0.0,4.4,3.0,3.0,6.0,4,285.0
286,58.0,0.0,4.0,170.0,225.0,1.0,2.0,146.0,1.0,2.8,2.0,2.0,6.0,2,286.0
291,55.0,0.0,2.0,132.0,342.0,0.0,0.0,166.0,0.0,1.2,1.0,0.0,3.0,0,291.0
293,63.0,1.0,4.0,140.0,187.0,0.0,2.0,144.0,1.0,4.0,1.0,2.0,7.0,2,293.0
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2,299.0

In [ ]:
filtro=np.less_equal(df.rest_blood_pressure,110)
df[filtro]

,age,sex,chest_pain_type,rest_blood_pressure,serum_cholesterol,fasting_blood_sugar,rest_ecg,max_HR_achieved,exercise_induced_angina,ST_depression,ST_slope,vessels_fluoroscopy,thal,heart_disease,new_col2
16,48.0,1.0,2.0,110.0,229.0,0.0,0.0,168.0,0.0,1.0,3.0,0.0,7.0,1,16.0
20,64.0,1.0,1.0,110.0,211.0,0.0,2.0,144.0,1.0,1.8,2.0,0.0,3.0,0,20.0
29,40.0,1.0,4.0,110.0,167.0,0.0,2.0,114.0,1.0,2.0,2.0,0.0,7.0,3,29.0
46,51.0,1.0,3.0,110.0,175.0,0.0,0.0,123.0,0.0,0.6,1.0,0.0,3.0,0,46.0
50,41.0,0.0,2.0,105.0,198.0,0.0,0.0,168.0,0.0,0.0,1.0,1.0,3.0,0,50.0
57,41.0,1.0,4.0,110.0,172.0,0.0,2.0,158.0,0.0,0.0,1.0,0.0,7.0,1,57.0
73,65.0,1.0,4.0,110.0,248.0,0.0,2.0,158.0,0.0,0.6,1.0,2.0,6.0,1,73.0
74,44.0,1.0,4.0,110.0,197.0,0.0,2.0,177.0,0.0,0.0,1.0,1.0,3.0,1,74.0
80,45.0,1.0,4.0,104.0,208.0,0.0,2.0,148.0,1.0,3.0,2.0,0.0,3.0,0,80.0
93,44.0,0.0,3.0,108.0,141.0,0.0,0.0,175.0,0.0,0.6,2.0,0.0,3.0,0,93.0
96,59.0,1.0,4.0,110.0,239.0,0.0,2.0,142.0,1.0,1.2,2.0,1.0,7.0,2,96.0
103,71.0,0.0,3.0,110.0,265.0,1.0,2.0,130.0,0.0,0.0,1.0,1.0,3.0,0,103.0
105,54.0,1.0,2.0,108.0,309.0,0.0,0.0,156.0,0.0,0.0,1.0,0.0,7.0,0,105.0
122,51.0,1.0,3.0,100.0,222.0,0.0,0.0,143.0,1.0,1.2,2.0,0.0,3.0,0,122.0
127,54.0,1.0,4.0,110.0,239.0,0.0,0.0,126.0,1.0,2.8,2.0,1.0,7.0,3,127.0
131,51.0,1.0,3.0,94.0,227.0,0.0,0.0,154.0,1.0,0.0,1.0,1.0,7.0,0,131.0
144,58.0,1.0,3.0,105.0,240.0,0.0,2.0,154.0,1.0,0.6,2.0,0.0,7.0,0,144.0
145,47.0,1.0,3.0,108.0,243.0,0.0,0.0,152.0,0.0,0.0,1.0,0.0,3.0,1,145.0
149,60.0,0.0,3.0,102.0,318.0,0.0,0.0,160.0,0.0,0.0,1.0,1.0,3.0,0,149.0
151,42.0,0.0,4.0,102.0,265.0,0.0,2.0,122.0,0.0,0.6,2.0,0.0,3.0,0,151.0
160,46.0,1.0,2.0,101.0,197.0,1.0,0.0,156.0,0.0,0.0,1.0,0.0,7.0,0,160.0
162,54.0,0.0,3.0,110.0,214.0,0.0,0.0,158.0,0.0,1.6,2.0,0.0,3.0,0,162.0
163,58.0,0.0,4.0,100.0,248.0,0.0,2.0,122.0,0.0,1.0,2.0,0.0,3.0,0,163.0
176,52.0,1.0,4.0,108.0,233.0,1.0,0.0,147.0,0.0,0.1,1.0,3.0,7.0,0,176.0
195,67.0,1.0,4.0,100.0,299.0,0.0,2.0,125.0,1.0,0.9,2.0,2.0,3.0,3,195.0
200,50.0,0.0,4.0,110.0,254.0,0.0,2.0,159.0,0.0,0.0,1.0,0.0,3.0,0,200.0
204,43.0,1.0,4.0,110.0,211.0,0.0,0.0,161.0,0.0,0.0,1.0,0.0,7.0,0,204.0
216,46.0,0.0,2.0,105.0,204.0,0.0,0.0,172.0,0.0,0.0,1.0,0.0,3.0,0,216.0
221,54.0,0.0,3.0,108.0,267.0,0.0,2.0,167.0,0.0,0.0,1.0,0.0,3.0,0,221.0
222,39.0,0.0,3.0,94.0,199.0,0.0,0.0,179.0,0.0,0.0,1.0,0.0,3.0,0,222.0
224,63.0,0.0,4.0,108.0,269.0,0.0,0.0,169.0,1.0,1.8,2.0,2.0,3.0,1,224.0
228,54.0,1.0,4.0,110.0,206.0,0.0,2.0,108.0,1.0,0.0,2.0,1.0,3.0,3,228.0
240,41.0,1.0,2.0,110.0,235.0,0.0,0.0,153.0,0.0,0.0,1.0,0.0,3.0,0,240.0
246,58.0,1.0,4.0,100.0,234.0,0.0,0.0,156.0,0.0,0.1,1.0,1.0,7.0,2,246.0
247,47.0,1.0,4.0,110.0,275.0,0.0,2.0,118.0,1.0,1.0,2.0,1.0,3.0,1,247.0
250,57.0,1.0,4.0,110.0,201.0,0.0,0.0,126.0,1.0,1.5,2.0,0.0,6.0,0,250.0
256,67.0,0.0,4.0,106.0,223.0,0.0,0.0,142.0,0.0,0.3,1.0,2.0,3.0,0,256.0
280,57.0,1.0,4.0,110.0,335.0,0.0,0.0,143.0,1.0,3.0,2.0,1.0,7.0,2,280.0
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1,298.0

We can also transpose the columns and rows of a dataframe, maybe for easeness of visualization

In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,293,294,295,296,297,298,299,300,301,302
age,63.0,67.0,67.0,37.0,41.0,56.0,62.0,57.0,63.0,53.0,...,63.0,63.0,41.0,59.0,57.0,45.0,68.0,57.0,57.0,38.0
sex,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
chest_pain_type,1.0,4.0,4.0,3.0,2.0,2.0,4.0,4.0,4.0,4.0,...,4.0,4.0,2.0,4.0,4.0,1.0,4.0,4.0,2.0,3.0
rest_blood_pressure,145.0,160.0,120.0,130.0,130.0,120.0,140.0,120.0,130.0,140.0,...,140.0,124.0,120.0,164.0,140.0,110.0,144.0,130.0,130.0,138.0
serum_cholesterol,233.0,286.0,229.0,250.0,204.0,236.0,268.0,354.0,254.0,203.0,...,187.0,197.0,157.0,176.0,241.0,264.0,193.0,131.0,236.0,175.0
fasting_blood_sugar,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
rest_ecg,2.0,2.0,2.0,0.0,2.0,0.0,2.0,0.0,2.0,2.0,...,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0
max_HR_achieved,150.0,108.0,129.0,187.0,172.0,178.0,160.0,163.0,147.0,155.0,...,144.0,136.0,182.0,90.0,123.0,132.0,141.0,115.0,174.0,173.0
exercise_induced_angina,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
ST_depression,2.3,1.5,2.6,3.5,1.4,0.8,3.6,0.6,1.4,3.1,...,4.0,0.0,0.0,1.0,0.2,1.2,3.4,1.2,0.0,0.0
ST_slope,3.0,2.0,2.0,3.0,1.0,1.0,3.0,1.0,2.0,3.0,...,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0
vessels_fluoroscopy,0.0,3.0,2.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,...,2.0,0.0,0.0,2.0,0.0,0.0,2.0,1.0,1.0,?
thal,6.0,3.0,7.0,3.0,3.0,3.0,3.0,3.0,7.0,7.0,...,7.0,3.0,3.0,6.0,7.0,7.0,7.0,7.0,3.0,3.0
heart_disease,0,2,1,0,0,0,3,0,2,1,...,2,1,0,3,1,1,2,3,1,0
new_col2,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,293.0,294.0,295.0,296.0,297.0,298.0,299.0,NaN,NaN,NaN

If we want to sort the elements of the dataframe in a different order we can use sort_values or sort_index. In both cases, pandas assumes an ascending order by default, so we have to tell it if we don't want it that way

In [ ]:
df.sort_index(ascending=False)

,age,sex,chest_pain_type,rest_blood_pressure,serum_cholesterol,fasting_blood_sugar,rest_ecg,max_HR_achieved,exercise_induced_angina,ST_depression,ST_slope,vessels_fluoroscopy,thal,heart_disease,new_col2
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0,NaN
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1,NaN
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3,NaN
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2,299.0
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1,298.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0,4.0
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0,3.0
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1,2.0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2,1.0
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0,0.0

In [ ]:
df_small.sort_index(ascending=False)

   col1  col2
d   NaN   8.0
c   3.0   NaN
b   2.0   6.0
a   1.0   5.0

the function "groupby" lets us group the elements of the dataframe based on the values of a given column, or group of columns

In [ ]:
df.groupby(by='heart_disease')['heart_disease'].count()

heart_disease
0    164
1     55
2     36
3     35
4     13
Name: heart_disease, dtype: int64

In [ ]:
df.groupby(by=['heart_disease','sex'])['age'].count().reset_index(name='counts')

   heart_disease  sex  counts
0              0  0.0      72
1              0  1.0      92
2              1  0.0       9
3              1  1.0      46
4              2  0.0       7
5              2  1.0      29
6              3  0.0       7
7              3  1.0      28
8              4  0.0       2
9              4  1.0      11

We can also apply functions (anonymous or otherwise) to all the elements of the dataframe, but we have to be careful to check if the data types are compatible with a given function

In [ ]:
df.select_dtypes(include=['float64','int64']).apply(np.sqrt)

,age,sex,chest_pain_type,rest_blood_pressure,serum_cholesterol,fasting_blood_sugar,rest_ecg,max_HR_achieved,exercise_induced_angina,ST_depression,ST_slope,heart_disease,new_col2
0,7.937254,1.0,1.000000,12.041595,15.264338,1.0,1.414214,12.247449,0.0,1.516575,1.732051,0.000000,0.000000
1,8.185353,1.0,2.000000,12.649111,16.911535,0.0,1.414214,10.392305,1.0,1.224745,1.414214,1.414214,1.000000
2,8.185353,1.0,2.000000,10.954451,15.132746,0.0,1.414214,11.357817,1.0,1.612452,1.414214,1.000000,1.414214
3,6.082763,1.0,1.732051,11.401754,15.811388,0.0,0.000000,13.674794,0.0,1.870829,1.732051,0.000000,1.732051
4,6.403124,0.0,1.414214,11.401754,14.282857,0.0,1.414214,13.114877,0.0,1.183216,1.000000,0.000000,2.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,6.708204,1.0,1.000000,10.488088,16.248077,0.0,0.000000,11.489125,0.0,1.095445,1.414214,1.000000,17.262677
299,8.246211,1.0,2.000000,12.000000,13.892444,1.0,0.000000,11.874342,0.0,1.843909,1.414214,1.414214,17.291616
300,7.549834,1.0,2.000000,11.401754,11.445523,0.0,0.000000,10.723805,1.0,1.095445,1.414214,1.732051,NaN
301,7.549834,0.0,1.414214,11.401754,15.362291,0.0,1.414214,13.190906,0.0,0.000000,1.414214,1.000000,NaN
302,6.164414,1.0,1.732051,11.747340,13.228757,0.0,0.000000,13.152946,0.0,0.000000,1.000000,0.000000,NaN

In [ ]:
df.select_dtypes(include=['float64','int64']).apply(lambda x:x*3)

,age,sex,chest_pain_type,rest_blood_pressure,serum_cholesterol,fasting_blood_sugar,rest_ecg,max_HR_achieved,exercise_induced_angina,ST_depression,ST_slope,heart_disease,new_col2
0,189.0,3.0,3.0,435.0,699.0,3.0,6.0,450.0,0.0,6.9,9.0,0,0.0
1,201.0,3.0,12.0,480.0,858.0,0.0,6.0,324.0,3.0,4.5,6.0,6,3.0
2,201.0,3.0,12.0,360.0,687.0,0.0,6.0,387.0,3.0,7.8,6.0,3,6.0
3,111.0,3.0,9.0,390.0,750.0,0.0,0.0,561.0,0.0,10.5,9.0,0,9.0
4,123.0,0.0,6.0,390.0,612.0,0.0,6.0,516.0,0.0,4.2,3.0,0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,135.0,3.0,3.0,330.0,792.0,0.0,0.0,396.0,0.0,3.6,6.0,3,894.0
299,204.0,3.0,12.0,432.0,579.0,3.0,0.0,423.0,0.0,10.2,6.0,6,897.0
300,171.0,3.0,12.0,390.0,393.0,0.0,0.0,345.0,3.0,3.6,6.0,9,NaN
301,171.0,0.0,6.0,390.0,708.0,0.0,6.0,522.0,0.0,0.0,6.0,3,NaN
302,114.0,3.0,9.0,414.0,525.0,0.0,0.0,519.0,0.0,0.0,3.0,0,NaN

We can display some dataframe's statistics my using describe()

In [ ]:
df.describe()

,age,sex,chest_pain_type,rest_blood_pressure,serum_cholesterol,fasting_blood_sugar,rest_ecg,max_HR_achieved,exercise_induced_angina,ST_depression,ST_slope,heart_disease,new_col2
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,300.000000
mean,54.438944,0.679868,3.158416,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.937294,149.500000
std,9.038662,0.467299,0.960126,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,1.228536,86.746758
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,74.750000
50%,56.000000,1.000000,3.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000,149.500000
75%,61.000000,1.000000,4.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,2.000000,224.250000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,4.000000,299.000000

Or we can directly ask for some statistic value...

In [ ]:
df.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

age                         54.438944
sex                          0.679868
chest_pain_type              3.158416
rest_blood_pressure        131.689769
serum_cholesterol          246.693069
fasting_blood_sugar          0.148515
rest_ecg                     0.990099
max_HR_achieved            149.607261
exercise_induced_angina      0.326733
ST_depression                1.039604
ST_slope                     1.600660
heart_disease                0.937294
new_col2                   149.500000
dtype: float64

If we want to save the dataframe to a file, we can use the to_csv function

In [ ]:
df2=df.select_dtypes(include=['float64','int64']).apply(lambda x:x%2)
df2.to_csv('df2.csv')

#Introduction to data visualization

We can also import datasets directly in excel format

In [ ]:
df_hmcia= pd.read_excel('datahmcia.xlsx', sheet_name='data')

FileNotFoundError: ignored

In [ ]:
df

In [ ]:
df_hmcia

Let's check the answer times for every answer and question

In [ ]:
df_hmcia.iloc[:,21:41]

We can change these times so they represent time in seconds

In [ ]:
for x in range(0,len(df_hmcia)): 
  for y in range(21,41):
    t_q=int(df_hmcia.iloc[x,y].second + df_hmcia.iloc[x,y].minute*60 + df_hmcia.iloc[x,y].hour*3600)
    df_hmcia.iloc[x,y]=t_q
display(df_hmcia.iloc[:,21:41])

## Matplotlib

This package let us create different kinds of plots

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

We can draw line plots

In [ ]:
y=df_hmcia.iloc[1,21:41]
plt.plot(y)
y2=df_hmcia.iloc[2,21:41]
plt.plot(y2)
y3=df_hmcia.iloc[3,21:41]
plt.plot(y3)

We can also change the markers and colors

In [ ]:
plt.plot(y,'or')
plt.plot(y2,'xb')
plt.plot(y3,'.y')

In [ ]:
x=np.array([*range(1,21)])
plt.plot(x,y,'--',linewidth=1)
print(y.shape)

Some plots need to be resized, and it's useful to include a legend

In [ ]:
plt.rcParams['figure.figsize'] = [20, 5]
plt.xticks(np.arange(min(x), max(x)+1, 1.0))
plt.plot(x,y,'--',linewidth=3,label='s1')
plt.legend(bbox_to_anchor =(0,1.1))

Histogram let us see the frequency of certain values

In [ ]:
plt.hist(df_hmcia.E10)
matplotlib.rcParams.update(matplotlib.rcParamsDefault)
plt.xticks(np.arange(min(df_hmcia.E10), max(df_hmcia.E10)+1, 1.0))

In [ ]:
plt.hist(df_hmcia.TQ10)

Some times, we want to take into account several columns at the same time

In [ ]:
question_times=np.array(df_hmcia.iloc[:,21:41])
question_times=question_times.flatten()
plt.hist(question_times, range=(0,30),color='red')

Bar charts are useful to compare several subjects with regard to one variable

In [ ]:
nota=5*(np.sum(df_hmcia.iloc[:,1:21],axis=1)/20)
labels=df_hmcia.Estudiante
plt.xticks(range(len(nota)), labels)
plt.yticks([0,1,2,3,4,5])
plt.xlabel('Estudiante')
plt.ylabel('Nota del quiz')
plt.title('Notas de los estudiantes en el quiz')
plt.bar(range(len(nota)), nota) 
plt.rcParams['figure.figsize'] = [15, 5]
plt.show()

In [ ]:
nota=5*(np.sum(df_hmcia.iloc[:,1:21],axis=1)/20)
print(nota)

In [ ]:
autoconfianza=5*np.mean(df_hmcia.iloc[:,41:65],axis=1)/2
labels=df_hmcia.Estudiante
plt.xticks(range(len(autoconfianza)), labels)
plt.yticks([0,1,2,3,4,5])
plt.xlabel('Estudiante')
plt.ylabel('Autoconfianza')
plt.title('Autoconfianza de los estudiantes en los temas de Python')
plt.bar(range(len(autoconfianza)), autoconfianza, color='red') 
plt.rcParams['figure.figsize'] = [15, 5]
plt.show()

And we can also compare several variables

In [ ]:
#plt.bar(x_axis -0.2, female, width=0.4, label = 'Female')
#plt.bar(x_axis +0.2, male, width=0.4, label = 'Male')

width =0.3
plt.bar(np.arange(len(nota)), nota, width=width, label='nota') 
plt.bar(np.arange(len(autoconfianza))+width, autoconfianza, color='red', width=width, label='autoconfianza') 
labels=df_hmcia.Estudiante
plt.xticks(range(len(autoconfianza)), labels)
plt.legend()
plt.show()